(()=>{"use strict";const C=window.OnlineCADCore;if(!C)return;
const stage=C.stage,base=C.canvas,ov=document.createElement("canvas");ov.id="drawingDisplayOverlay";Object.assign(ov.style,{position:"absolute",inset:"0",width:"100%",height:"100%",pointerEvents:"none",zIndex:"440"});stage.appendChild(ov);const x=ov.getContext("2d");let dpr=1;
const drawPage=document.querySelector('.tabpage[data-page="draw"]');if(drawPage){const g=document.createElement("div");g.className="group tabpage drawing-display hidden";g.dataset.page="draw";g.innerHTML='<div class="checks"><label title="Çizgi ve poligon köşelerini yuvarlak işaretle"><input id="balastro" type="checkbox" checked> Balastro</label><label title="Kenar uzunluklarını çizgi üzerinde göster"><input id="edgeMeters" type="checkbox" checked> Metreler</label></div><em>Çizgi Görünümü</em>';drawPage.insertAdjacentElement("afterend",g)}
function dist(a,b){const R=6371008.8,r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dp=(b.lat-a.lat)*r,dl=(b.lng-a.lng)*r,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function marker(p){let q=C.toPixel(p);x.beginPath();x.arc(q.x,q.y,4.5,0,Math.PI*2);x.fillStyle="#fff";x.fill();x.lineWidth=1.8;x.strokeStyle="#00a9bd";x.stroke()}
function label(a,b){let A=C.toPixel(a),B=C.toPixel(b),dx=B.x-A.x,dy=B.y-A.y,L=Math.hypot(dx,dy);if(L<34)return;let mx=(A.x+B.x)/2,my=(A.y+B.y)/2,nx=-dy/L,ny=dx/L,text=dist(a,b).toFixed(2)+" m";x.save();x.font="600 11px Arial";let w=x.measureText(text).width+10,px=mx+nx*13,py=my+ny*13;x.fillStyle="rgba(255,255,255,.88)";x.strokeStyle="rgba(30,45,52,.28)";x.lineWidth=1;x.beginPath();x.roundRect(px-w/2,py-9,w,18,4);x.fill();x.stroke();x.fillStyle="#26343b";x.textAlign="center";x.textBaseline="middle";x.fillText(text,px,py);x.restore()}
function paint(){x.clearRect(0,0,ov.width/dpr,ov.height/dpr);let dots=document.getElementById("balastro")?.checked!==false,meters=document.getElementById("edgeMeters")?.checked!==false;for(const o of C.getObjects()){if((o.type!=="line"&&o.type!=="poly")||!o.pts?.length)continue;if(meters&&o.pts.length>1){let n=o.type==="poly"?o.pts.length:o.pts.length-1;for(let i=0;i<n;i++)label(o.pts[i],o.pts[(i+1)%o.pts.length])}if(dots)o.pts.forEach(marker)}}
function resize(){let r=stage.getBoundingClientRect();dpr=devicePixelRatio||1;ov.width=Math.max(1,Math.round(r.width*dpr));ov.height=Math.max(1,Math.round(r.height*dpr));x.setTransform(dpr,0,0,dpr,0,0);paint()}
document.getElementById("balastro")?.addEventListener("change",paint);document.getElementById("edgeMeters")?.addEventListener("change",paint);
base.addEventListener("click",()=>setTimeout(paint,0));base.addEventListener("contextmenu",()=>setTimeout(paint,0));window.addEventListener("keyup",()=>setTimeout(paint,0));document.addEventListener("click",e=>{if(e.target.closest("button"))setTimeout(paint,30)});
C.map.on("move zoom",paint);new ResizeObserver(resize).observe(stage);resize();window.OnlineCADExtensions.drawingDisplay={redraw:paint};
})();