(()=>{"use strict";
const C=window.OnlineCADCore;if(!C)return;const mapPage=document.querySelector('.tabpage[data-page="map"]');if(!mapPage)return;
const g=document.createElement("div");g.className="group tabpage dxf-io hidden";g.dataset.page="map";g.innerHTML='<div class="bigtools"><button data-dxf="open"><i>DXF</i><span>DXF Aç</span></button><button data-dxf="save"><i>⇩</i><span>DXF Kaydet</span></button></div><em>DXF</em><input id="dxfFile" type="file" accept=".dxf,text/plain" hidden>';mapPage.insertAdjacentElement("afterend",g);const inp=g.querySelector("#dxfFile");
function def(k,c){return k==="itrf"?"+proj=tmerc +lat_0=0 +lon_0="+c+" +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +units=m +no_defs":"+proj=tmerc +lat_0=0 +lon_0="+c+" +k=1 +x_0=500000 +y_0=0 +ellps=intl +towgs84=-84,-97,-117 +units=m +no_defs"}
function pairs(t){let a=t.replace(/\r/g,"").split("\n"),r=[];for(let i=0;i+1<a.length;i+=2)r.push([a[i].trim(),a[i+1].trim()]);return r}
function raw(t){let p=pairs(t),out=[];for(let i=0;i<p.length;i++){if(p[i][0]!=="0")continue;let typ=p[i][1];if(typ==="LINE"){let x1,y1,x2,y2;for(i++;i<p.length&&p[i][0]!=="0";i++){let[c,v]=p[i];if(c==="10")x1=+v;if(c==="20")y1=+v;if(c==="11")x2=+v;if(c==="21")y2=+v}i--;if([x1,y1,x2,y2].every(Number.isFinite))out.push({type:"line",xy:[[x1,y1],[x2,y2]]})}else if(typ==="POINT"){let x,y;for(i++;i<p.length&&p[i][0]!=="0";i++){let[c,v]=p[i];if(c==="10")x=+v;if(c==="20")y=+v}i--;if(Number.isFinite(x)&&Number.isFinite(y))out.push({type:"point",xy:[[x,y]]})}else if(typ==="LWPOLYLINE"){let a=[],x=null,closed=false;for(i++;i<p.length&&p[i][0]!=="0";i++){let[c,v]=p[i];if(c==="70")closed=(+v&1)!==0;if(c==="10")x=+v;if(c==="20"&&x!==null){a.push([x,+v]);x=null}}i--;if(a.length>1)out.push({type:closed&&a.length>2?"poly":"line",xy:a})}}return out}
function modal(file,items){let old=document.getElementById("dxfImportDialog");if(old)old.remove();let first=items.flatMap(o=>o.xy)[0]||[0,0],d=document.createElement("div");d.id="dxfImportDialog";Object.assign(d.style,{position:"fixed",inset:"0",zIndex:"5000",background:"rgba(0,0,0,.45)",display:"grid",placeItems:"center"});d.innerHTML='<div style="width:min(440px,92vw);background:#fff;border-radius:10px;padding:18px;font:13px Arial;color:#20262c;box-shadow:0 12px 40px #0006"><b style="font-size:16px">DXF Koordinat Sistemi</b><p style="line-height:1.45">Dosya: <b>'+file.name.replace(/[<>&]/g,"")+'</b><br>İlk koordinat: <b>'+first[0].toFixed(3)+" / "+first[1].toFixed(3)+'</b></p><label>Sistem</label><select id="dxfSys" style="width:100%;padding:8px;margin:5px 0 12px"><option value="itrf">ITRF96 / TM3 (3°)</option><option value="ed50">ED50 / TM3 (3°)</option><option value="wgs">WGS84 Enlem/Boylam</option></select><label id="dxfDomLabel">Dilim Orta Meridyeni (DOM)</label><select id="dxfDom" style="width:100%;padding:8px;margin:5px 0 12px"><option>27</option><option>30</option><option selected>33</option><option>36</option><option>39</option><option>42</option><option>45</option></select><label style="display:flex;gap:8px;align-items:center;margin:6px 0 15px"><input id="dxfSwap" type="checkbox"> X/Y koordinatlarını ters yorumla</label><div id="dxfWarn" style="background:#f5f6f7;padding:9px;border-radius:6px;margin-bottom:12px">DXF koordinatları seçilen sisteme göre WGS84 harita koordinatına dönüştürülecek.</div><div style="display:flex;justify-content:flex-end;gap:8px"><button id="dxfCancel" style="padding:8px 14px">Vazgeç</button><button id="dxfApply" style="padding:8px 14px;font-weight:700">Yükle</button></div></div>';document.body.appendChild(d);
let sys=d.querySelector("#dxfSys"),dom=d.querySelector("#dxfDom"),lab=d.querySelector("#dxfDomLabel");sys.onchange=()=>{let w=sys.value==="wgs";dom.disabled=w;lab.style.opacity=w?".45":"1"};d.querySelector("#dxfCancel").onclick=()=>d.remove();d.querySelector("#dxfApply").onclick=()=>{try{let os=convert(items,sys.value,+dom.value,d.querySelector("#dxfSwap").checked);let bad=os.flatMap(o=>o.pts).some(p=>!Number.isFinite(p.lat)||!Number.isFinite(p.lng)||Math.abs(p.lat)>90||Math.abs(p.lng)>180);if(bad)throw Error("Dönüşüm geçerli dünya koordinatı üretmedi. Sistem, DOM veya X/Y seçimini kontrol edin.");os.forEach(o=>C.addObject(o));let a=os.flatMap(o=>o.pts).map(p=>[p.lat,p.lng]);if(a.length)C.map.fitBounds(a,{padding:[50,50],maxZoom:20});document.getElementById("crs").value=sys.value;document.getElementById("cm").value=String(dom.value);d.remove();C.showTip(os.length+" DXF nesnesi yüklendi");setTimeout(()=>C.showTip(""),1800)}catch(e){d.querySelector("#dxfWarn").textContent=e.message;d.querySelector("#dxfWarn").style.background="#ffe6e0"}}}
function convert(items,k,c,swap){return items.map(o=>({type:o.type,pts:o.xy.map(v=>{let x=swap?v[1]:v[0],y=swap?v[0]:v[1];if(k==="wgs"){let p={lat:y,lng:x};if(Math.abs(p.lat)>90||Math.abs(p.lng)>180)throw Error("Bu değerler WGS84 enlem/boylam aralığında değil.");return p}let q=proj4(def(k,c),"EPSG:4326",[x,y]);return{lat:q[1],lng:q[0]}})}))}
function fromLL(p){let k=document.getElementById("crs").value,c=+document.getElementById("cm").value;if(k==="wgs")return[p.lng,p.lat];return proj4("EPSG:4326",def(k,c),[p.lng,p.lat])}
function download(name,text){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"application/dxf"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportDXF(){let os=C.getObjects(),s="0\nSECTION\n2\nHEADER\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n";for(let o of os){if(!o.pts?.length)continue;if(o.type==="point"){let q=fromLL(o.pts[0]);s+="0\nPOINT\n8\nONLINECAD\n10\n"+q[0]+"\n20\n"+q[1]+"\n30\n0\n"}else{let flag=o.type==="poly"?1:0;s+="0\nLWPOLYLINE\n8\nONLINECAD\n90\n"+o.pts.length+"\n70\n"+flag+"\n";for(let p of o.pts){let q=fromLL(p);s+="10\n"+q[0]+"\n20\n"+q[1]+"\n"}}}s+="0\nENDSEC\n0\nEOF\n";download("onlinecad_"+new Date().toISOString().slice(0,10)+".dxf",s);C.showTip(os.length+" nesne DXF olarak kaydedildi");setTimeout(()=>C.showTip(""),1500)}
inp.onchange=async()=>{let f=inp.files?.[0];if(!f)return;try{let items=raw(await f.text());if(!items.length){alert("Desteklenen DXF nesnesi bulunamadı. LINE, POINT ve LWPOLYLINE destekleniyor.");return}modal(f,items)}catch(e){alert("DXF okunamadı: "+e.message)}finally{inp.value=""}};g.querySelector('[data-dxf="open"]').onclick=()=>inp.click();g.querySelector('[data-dxf="save"]').onclick=exportDXF;window.OnlineCADExtensions.dxfIO={raw,convert,exportDXF};
})();