(()=>{"use strict";const C=window.OnlineCADCore;if(!C)return;const edit=document.querySelector('.tabpage[data-page="edit"]');if(!edit)return;
const g=document.createElement("div");g.className="group tabpage line-editing hidden";g.dataset.page="edit";g.innerHTML='<div class="bigtools"><button data-led="extend"><i>↗</i><span>Uzat/Kısalt</span></button><button data-led="break"><i>✂</i><span>Kır</span></button><button data-led="join"><i>⛓</i><span>Birleştir</span></button><button data-led="fillet"><i>◜</i><span>Yuvarlat</span></button></div><em>Çizgi İşlemleri</em>';edit.insertAdjacentElement("afterend",g);
const cv=C.canvas;let mode="",active=false,first=null;
function stop(){active=false;mode="";first=null;g.querySelectorAll("button").forEach(b=>b.classList.remove("active"));C.resumeCore()}
function start(m,b){stop();active=true;mode=m;b.classList.add("active");C.stopCore();C.showTip(m==="join"?"Birinci çizgiyi tıkla":m==="fillet"?"Köşesi olan çizgiyi tıkla":"Çizgiyi tıkla")}
function segdist(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{d:1e9,t:0};let t=((p.x-a.x)*dx+(p.y-a.y)*dy)/l,t0=Math.max(0,Math.min(1,t)),x=a.x+t0*dx,y=a.y+t0*dy;return{d:Math.hypot(p.x-x,p.y-y),t:t0}}
function pick(q){let P=C.toPixel(q),os=C.getObjects(),best=null,bd=14;os.forEach((o,i)=>{if(o.type!=="line"||o.pts.length<2)return;for(let k=0;k<o.pts.length-1;k++){let z=segdist(P,C.toPixel(o.pts[k]),C.toPixel(o.pts[k+1]));if(z.d<bd){bd=z.d;best={i,o,k,t:z.t}}}});return best}
function interp(a,b,t){return{lat:a.lat+(b.lat-a.lat)*t,lng:a.lng+(b.lng-a.lng)*t}}
function meters(a,b){const R=6378137,k=Math.cos(a.lat*Math.PI/180);return{x:(b.lng-a.lng)*Math.PI/180*R*k,y:(b.lat-a.lat)*Math.PI/180*R}}
function ll(o,x,y){const R=6378137,k=Math.cos(o.lat*Math.PI/180);return{lat:o.lat+y/R*180/Math.PI,lng:o.lng+x/(R*k)*180/Math.PI}}
function dialog(title,html,fn){let m=document.getElementById("modal"),mt=document.getElementById("mt"),mb=document.getElementById("mb"),mo=document.getElementById("mo"),mc=document.getElementById("mc"),mx=document.getElementById("mx");mt.textContent=title;mb.innerHTML=html;m.classList.add("show");let close=()=>m.classList.remove("show");mc.onclick=mx.onclick=close;mo.onclick=()=>{if(fn()!==false)close()}}
function click(e){if(!active)return;e.preventDefault();e.stopImmediatePropagation();let q=C.snapPoint(C.fromPixel(e.offsetX,e.offsetY)),h=pick(q);if(!h){C.showTip("Çizgi bulunamadı");return}
if(mode==="break"){let a=h.o.pts[h.k],b=h.o.pts[h.k+1],x=interp(a,b,h.t),p1=h.o.pts.slice(0,h.k+1).concat([x]),p2=[x].concat(h.o.pts.slice(h.k+1));if(p1.length>1&&p2.length>1){C.replaceObject(h.i,{type:"line",pts:p1});C.addObject({type:"line",pts:p2})}stop();return}
if(mode==="join"){if(!first){first=h;C.showTip("İkinci çizgiyi tıkla");return}if(first.i===h.i){C.showTip("Farklı bir çizgi seç");return}let A=first.o.pts,B=h.o.pts,ends=[[0,0],[0,B.length-1],[A.length-1,0],[A.length-1,B.length-1]],best=ends[0],bd=1e99;for(let z of ends){let p=C.toPixel(A[z[0]]),r=C.toPixel(B[z[1]]),d=Math.hypot(p.x-r.x,p.y-r.y);if(d<bd){bd=d;best=z}}let aa=best[0]===0?[...A].reverse():[...A],bb=best[1]===B.length-1?[...B].reverse():[...B],joined=aa.concat(bb);let hi=Math.max(first.i,h.i),lo=Math.min(first.i,h.i);C.replaceObject(lo,{type:"line",pts:joined});C.removeObject(hi);stop();return}
if(mode==="extend"){let o=h.o,nearStart=h.k===0&&h.t<.5,nearEnd=h.k===o.pts.length-2&&h.t>=.5;if(!nearStart&&!nearEnd){C.showTip("Çizginin başlangıç veya bitiş ucuna yakın tıkla");return}dialog("Uzat / Kısalt",'<label>Mesafe (m)</label><input id="leDist" type="number" value="5" step="0.001"><small>Pozitif uzatır, negatif kısaltır.</small>',()=>{let d=+document.getElementById("leDist").value;if(!Number.isFinite(d))return false;let pts=[...o.pts],i=nearStart?0:pts.length-1,j=nearStart?1:pts.length-2,v=meters(pts[j],pts[i]),L=Math.hypot(v.x,v.y);if(!L)return false;pts[i]=ll(pts[i],v.x/L*d,v.y/L*d);C.replaceObject(h.i,{type:"line",pts});stop()});return}
if(mode==="fillet"){let o=h.o;if(o.pts.length<3){C.showTip("En az 3 köşeli çizgi gerekli");return}let vertex=Math.min(o.pts.length-2,Math.max(1,h.k+(h.t>.5?1:0)));dialog("Köşe Yuvarlat",'<label>Yarıçap (m)</label><input id="leRad" type="number" value="2" step="0.001">',()=>{let r=+document.getElementById("leRad").value;if(!(r>0))return false;let a=o.pts[vertex-1],v=o.pts[vertex],b=o.pts[vertex+1],A=meters(v,a),B=meters(v,b),la=Math.hypot(A.x,A.y),lb=Math.hypot(B.x,B.y),ua={x:A.x/la,y:A.y/la},ub={x:B.x/lb,y:B.y/lb},ang=Math.acos(Math.max(-1,Math.min(1,ua.x*ub.x+ua.y*ub.y))),t=r/Math.tan(ang/2);if(!isFinite(t)||t>=la||t>=lb)return false;let p1=ll(v,ua.x*t,ua.y*t),p2=ll(v,ub.x*t,ub.y*t),bis={x:ua.x+ub.x,y:ua.y+ub.y},bl=Math.hypot(bis.x,bis.y),cd=r/Math.sin(ang/2),cen=ll(v,bis.x/bl*cd,bis.y/bl*cd),X1=meters(cen,p1),X2=meters(cen,p2),a1=Math.atan2(X1.y,X1.x),a2=Math.atan2(X2.y,X2.x),cross=ua.x*ub.y-ua.y*ub.x,tw=Math.PI*2,span=((a2-a1)%tw+tw)%tw;if(cross>0)span-=tw;let arc=[];for(let n=0;n<=16;n++){let z=a1+span*n/16;arc.push(ll(cen,Math.cos(z)*r,Math.sin(z)*r))}let pts=o.pts.slice(0,vertex).concat(arc,o.pts.slice(vertex+1));C.replaceObject(h.i,{type:"line",pts});stop()});}}
cv.addEventListener("click",click,true);window.addEventListener("keydown",e=>{if(active&&e.key==="Escape"){e.stopImmediatePropagation();stop()}},true);g.querySelectorAll("[data-led]").forEach(b=>b.onclick=()=>start(b.dataset.led,b));window.OnlineCADExtensions.lineEditing={stop};
})();