(()=>{"use strict";const C=window.OnlineCADCore;if(!C)return;const fixed=document.querySelector(".group.fixed");if(!fixed)return;
const box=document.createElement("div");box.className="group fixed snap-pro";box.innerHTML='<div class="checks"><label><input id="spNear" type="checkbox"> En yakın</label><label><input id="spInt" type="checkbox" checked> Kesişim</label><label><input id="spPerp" type="checkbox"> Dik ayak</label></div><em>Akıllı Yakalama</em>';fixed.insertAdjacentElement("afterend",box);
const cv=C.canvas,stage=C.stage,ov=document.createElement("canvas");ov.id="snapOverlay";Object.assign(ov.style,{position:"absolute",inset:"0",width:"100%",height:"100%",pointerEvents:"none",zIndex:"470"});stage.appendChild(ov);const x=ov.getContext("2d");let dpr=1,mark=null;
function closest(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{x:a.x,y:a.y,d:Math.hypot(p.x-a.x,p.y-a.y)};let t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)),xx=a.x+t*dx,yy=a.y+t*dy;return{x:xx,y:yy,d:Math.hypot(p.x-xx,p.y-yy)}}
function cross(a,b,c,d){let r={x:b.x-a.x,y:b.y-a.y},s={x:d.x-c.x,y:d.y-c.y},den=r.x*s.y-r.y*s.x;if(Math.abs(den)<1e-9)return null;let t=((c.x-a.x)*s.y-(c.y-a.y)*s.x)/den,u=((c.x-a.x)*r.y-(c.y-a.y)*r.x)/den;if(t<0||t>1||u<0||u>1)return null;return{x:a.x+t*r.x,y:a.y+t*r.y}}
function segs(){let z=[];C.getObjects().forEach(o=>{if(!o.pts||o.pts.length<2)return;let n=o.type==="poly"?o.pts.length:o.pts.length-1;for(let i=0;i<n;i++)z.push([o.pts[i],o.pts[(i+1)%o.pts.length]])});return z}
const old=C.snapPoint.bind(C);C.snapPoint=function(p){let P=C.toPixel(p),best=p,bd=12,kind="";let core=old(p),Q=C.toPixel(core),cd=Math.hypot(P.x-Q.x,P.y-Q.y);if(cd<bd){best=core;bd=cd;kind="nokta"}let ss=segs();
if(document.getElementById("spInt")?.checked)for(let i=0;i<ss.length;i++)for(let j=i+1;j<ss.length;j++){let q=cross(C.toPixel(ss[i][0]),C.toPixel(ss[i][1]),C.toPixel(ss[j][0]),C.toPixel(ss[j][1]));if(q){let d=Math.hypot(P.x-q.x,P.y-q.y);if(d<bd){bd=d;best=C.fromPixel(q.x,q.y);kind="kesişim"}}}
if(document.getElementById("spNear")?.checked||document.getElementById("spPerp")?.checked)for(let s of ss){let q=closest(P,C.toPixel(s[0]),C.toPixel(s[1]));if(q.d<bd){bd=q.d;best=C.fromPixel(q.x,q.y);kind=document.getElementById("spPerp")?.checked?"dik":"yakın"}}
mark=bd<12?{p:best,k:kind}:null;return best};
function paint(){x.clearRect(0,0,ov.width/dpr,ov.height/dpr);if(!mark)return;let p=C.toPixel(mark.p);x.save();x.strokeStyle="#ef8f18";x.fillStyle="rgba(255,255,255,.9)";x.lineWidth=2;x.beginPath();if(mark.k==="kesişim"){x.moveTo(p.x-6,p.y-6);x.lineTo(p.x+6,p.y+6);x.moveTo(p.x+6,p.y-6);x.lineTo(p.x-6,p.y+6)}else if(mark.k==="dik")x.rect(p.x-5,p.y-5,10,10);else{x.arc(p.x,p.y,6,0,Math.PI*2);x.fill()}x.stroke();x.font="11px Arial";x.fillStyle="#ef8f18";x.fillText(mark.k,p.x+9,p.y-9);x.restore()}
function resize(){let r=stage.getBoundingClientRect();dpr=devicePixelRatio||1;ov.width=Math.round(r.width*dpr);ov.height=Math.round(r.height*dpr);x.setTransform(dpr,0,0,dpr,0,0);paint()}
cv.addEventListener("mousemove",()=>requestAnimationFrame(paint));cv.addEventListener("mouseleave",()=>{mark=null;paint()});C.map.on("move zoom",paint);new ResizeObserver(resize).observe(stage);resize();window.OnlineCADExtensions.snapPro={clear(){mark=null;paint()}}})();