(()=>{"use strict";const C=window.OnlineCADCore;if(!C)return;const ref=document.querySelector('.advanced-draw');if(!ref)return;
const g=document.createElement("div");g.className="group tabpage survey-draw";g.dataset.page="draw";g.innerHTML='<div class="bigtools"><button data-survey="polar"><i>∠</i><span>Boy+Açı</span></button><button data-survey="offset"><i>∥</i><span>Paralel</span></button><button data-survey="intersect"><i>✕</i><span>Kesişim</span></button></div><em>Haritacı</em>';ref.insertAdjacentElement("afterend",g);
const cv=C.canvas,map=C.map;let mode="",step=0,a=null,b=null,active=false;
function off(){active=false;mode="";step=0;a=b=null;g.querySelectorAll("button").forEach(x=>x.classList.remove("active"));C.resumeCore()}
function on(m,btn){off();active=true;mode=m;btn.classList.add("active");C.stopCore();if(m==="polar")C.showTip("Başlangıç noktasını tıkla");if(m==="offset")C.showTip("Paralel oluşturmak için çizginin iki noktasını tıkla");if(m==="intersect")C.showTip("1. doğrunun iki noktasını tıkla")}
function p(e){return C.snapPoint(C.fromPixel(e.offsetX,e.offsetY))}
function meters(a,b){const R=6378137,lat=(a.lat+b.lat)*Math.PI/360,dx=(b.lng-a.lng)*Math.PI/180*R*Math.cos(lat),dy=(b.lat-a.lat)*Math.PI/180*R;return{x:dx,y:dy}}
function fromMeters(o,x,y){const R=6378137,lat=o.lat*Math.PI/180;return{lat:o.lat+y/R*180/Math.PI,lng:o.lng+x/(R*Math.cos(lat))*180/Math.PI}}
function intersection(a,b,c,d){let A=meters(a,b),C0=meters(a,c),D=meters(a,d),rx=A.x,ry=A.y,sx=D.x-C0.x,sy=D.y-C0.y,den=rx*sy-ry*sx;if(Math.abs(den)<1e-9)return null;let t=(C0.x*sy-C0.y*sx)/den;return fromMeters(a,t*rx,t*ry)}
function dialog(title,html,ok){const modal=document.getElementById("modal"),mt=document.getElementById("mt"),mb=document.getElementById("mb"),mo=document.getElementById("mo"),mc=document.getElementById("mc"),mx=document.getElementById("mx");mt.textContent=title;mb.innerHTML=html;modal.classList.add("show");const close=()=>modal.classList.remove("show");mc.onclick=mx.onclick=close;mo.onclick=()=>{if(ok()!==false)close()}}
function click(e){if(!active)return;e.preventDefault();e.stopImmediatePropagation();let q=p(e);
if(mode==="polar"){if(!a){a=q;dialog("Boy + Açı",'<label>Uzunluk (m)</label><input id="svLen" type="number" value="10" step="0.001"><label>Açı birimi</label><select id="svUnit"><option value="grad">Grad</option><option value="deg">Derece</option></select><label>Kuzeyden saat yönünde açı</label><input id="svAng" type="number" value="100" step="0.0001">',()=>{let L=+document.getElementById("svLen").value,A=+document.getElementById("svAng").value,u=document.getElementById("svUnit").value;if(!(L>0)||!Number.isFinite(A))return false;let r=(u==="grad"?A*.9:A)*Math.PI/180,end=fromMeters(a,Math.sin(r)*L,Math.cos(r)*L);C.addObject({type:"line",pts:[a,end]});off()});}return}
if(mode==="offset"){if(step===0){a=q;step=1;C.showTip("Çizginin ikinci noktasını tıkla");return}if(step===1){b=q;step=2;dialog("Paralel Çizgi",'<label>Ofset mesafesi (m)</label><input id="svOff" type="number" value="5" step="0.001"><label>Taraf</label><select id="svSide"><option value="1">Sol</option><option value="-1">Sağ</option></select>',()=>{let d=+document.getElementById("svOff").value,s=+document.getElementById("svSide").value,v=meters(a,b),L=Math.hypot(v.x,v.y);if(!(L>0)||!Number.isFinite(d))return false;let ox=-v.y/L*d*s,oy=v.x/L*d*s;C.addObject({type:"line",pts:[fromMeters(a,ox,oy),fromMeters(a,v.x+ox,v.y+oy)]});off()});return}}
if(mode==="intersect"){if(step===0){a=q;step=1;C.showTip("1. doğrunun ikinci noktasını tıkla");return}if(step===1){b=q;step=2;C.showTip("2. doğrunun ilk noktasını tıkla");return}if(step===2){window.__svC=q;step=3;C.showTip("2. doğrunun ikinci noktasını tıkla");return}let x=intersection(a,b,window.__svC,q);if(!x){C.showTip("Doğrular paralel · tekrar dene");step=0;a=b=null;return}C.addObject({type:"point",pts:[x]});C.showTip("Kesişim noktası oluşturuldu");setTimeout(off,700)}}
cv.addEventListener("click",click,true);window.addEventListener("keydown",e=>{if(active&&e.key==="Escape"){e.stopImmediatePropagation();off()}},true);g.querySelectorAll("[data-survey]").forEach(btn=>btn.onclick=()=>on(btn.dataset.survey,btn));window.OnlineCADExtensions.surveyDrawing={stop:off};
})();