(()=>{"use strict";const C=window.OnlineCADCore;if(!C)return;const anchor=document.querySelector(".line-editing");if(!anchor)return;
const g=document.createElement("div");g.className="group tabpage vertex-tools hidden";g.dataset.page="edit";g.innerHTML='<div class="bigtools"><button data-vt="add"><i>＋</i><span>Köşe Ekle</span></button><button data-vt="del"><i>−</i><span>Köşe Sil</span></button><button data-vt="move"><i>◆</i><span>Köşe Taşı</span></button></div><em>Köşe Düzeltme</em>';anchor.insertAdjacentElement("afterend",g);
const cv=C.canvas;let mode="",active=false,pending=null;
function stop(){mode="";active=false;pending=null;g.querySelectorAll("button").forEach(b=>b.classList.remove("active"));C.resumeCore();window.OnlineCADExtensions.drawingDisplay?.redraw()}
function start(m,b){stop();mode=m;active=true;b.classList.add("active");C.stopCore();C.showTip(m==="add"?"Köşe eklenecek kenara tıkla":m==="del"?"Silinecek köşeye tıkla":"Taşınacak köşeye tıkla")}
function seg(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{d:1e9,t:0};let t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)),xx=a.x+t*dx,yy=a.y+t*dy;return{d:Math.hypot(p.x-xx,p.y-yy),t}}
function vertex(q){let P=C.toPixel(q),best=null,bd=14;C.getObjects().forEach((o,i)=>{if(o.type!=="line"&&o.type!=="poly")return;o.pts.forEach((p,k)=>{let Q=C.toPixel(p),d=Math.hypot(P.x-Q.x,P.y-Q.y);if(d<bd){bd=d;best={i,k,o}}})});return best}
function edge(q){let P=C.toPixel(q),best=null,bd=14;C.getObjects().forEach((o,i)=>{if((o.type!=="line"&&o.type!=="poly")||o.pts.length<2)return;let n=o.type==="poly"?o.pts.length:o.pts.length-1;for(let k=0;k<n;k++){let z=seg(P,C.toPixel(o.pts[k]),C.toPixel(o.pts[(k+1)%o.pts.length]));if(z.d<bd){bd=z.d;best={i,k,t:z.t,o}}}});return best}
cv.addEventListener("click",e=>{if(!active)return;e.preventDefault();e.stopImmediatePropagation();let raw=C.fromPixel(e.offsetX,e.offsetY),q=C.snapPoint(raw);
if(mode==="add"){let h=edge(raw);if(!h){C.showTip("Kenar bulunamadı");return}let a=h.o.pts[h.k],b=h.o.pts[(h.k+1)%h.o.pts.length],p={lat:a.lat+(b.lat-a.lat)*h.t,lng:a.lng+(b.lng-a.lng)*h.t},o=structuredClone(h.o);o.pts.splice(h.k+1,0,p);C.replaceObject(h.i,o);stop();return}
if(mode==="del"){let h=vertex(raw);if(!h){C.showTip("Köşe bulunamadı");return}let min=h.o.type==="poly"?3:2;if(h.o.pts.length<=min){C.showTip("Minimum köşe sayısına ulaşıldı");return}let o=structuredClone(h.o);o.pts.splice(h.k,1);C.replaceObject(h.i,o);stop();return}
if(mode==="move"){if(!pending){pending=vertex(raw);if(!pending){C.showTip("Köşe bulunamadı");return}C.selectObject(pending.i);C.showTip("Yeni konumu tıkla · Yakalama aktif");return}let o=structuredClone(pending.o);o.pts[pending.k]=q;C.replaceObject(pending.i,o);stop()}},true);
window.addEventListener("keydown",e=>{if(active&&e.key==="Escape"){e.stopImmediatePropagation();stop()}},true);g.querySelectorAll("[data-vt]").forEach(b=>b.onclick=()=>start(b.dataset.vt,b));window.OnlineCADExtensions.vertexTools={stop}})();